import { Poppins } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import { Providers } from "./providers";
import Head from "next/head";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
});

export const metadata = {
  title: "Umurava Challenge",
  description: "Generated by Create Next App",
  icons: {
    icon: "/images/logo1.png",
  },
};

interface RootLayoutProps {
  children: ReactNode;
}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/images/logo1.png" type="image/png" />
      </Head>

      <body className={poppins.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
